---
- name: Download Jenkins keys 
  apt_key: url=https://pkg.jenkins.io/debian/jenkins-ci.org.key state=present
  sudo: yes

- name: Add repository in sources list
  shell: sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
  sudo: yes

- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  sudo: yes

- name: Install jenkins
  apt: name=jenkins state=present
  sudo: yes
  notify: start jenkins

- wait_for:
    port: 8080
    host: "{{ inventory_hostname }}"
    delay: 10

- wait_for:
    path: /var/lib/jenkins/secrets/initialAdminPassword
  become: yes

- name: Getting admin password
  shell: cat /var/lib/jenkins/secrets/initialAdminPassword
  register: password
  become: yes

- jenkins_job:
   config: "{{ lookup('template', 'jobs/jenkinsjob.xml.j2') }}"
   name: CSC519HW1-B
   password: "{{ password.stdout }}"
   url: "http://{{ inventory_hostname }}:8080"
   user: admin
