git_host: github.ncsu.edu
itrust_repo: git@http://github.ncsu.edu/engr-csc326-staff/iTrust-v23.git

eclipse_workspace: /home/{{ ansible_user_id }}/code
code_directory: /home/{{ ansible_user_id }}/code/itrust

tomcat_url: http://www-eu.apache.org/dist/tomcat/tomcat-8/v8.0.33/bin/apache-tomcat-8.0.33.tar.gz
tomcat_version: 8.0.41
jdbc_url: http://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-5.1.38.zip
jdbc_version: 5.1.38

packages:
  - python-pip
  - gcc
  - python-setuptools
  - git-core
  - python-lxml
  - debconf-utils
  - libxml2-dev
  - libxslt-dev
