---
- name: Copy canary_LB.js file into remote server
  copy: src=canary_LB.js dest=.

- name: Copy ip text files to remote machine
  copy: src={{ item }} dest=.
  with_items: 
    - prodIp.txt 
    - canaryIp.txt

- name: Install forever globally
  command: sudo npm install forever --global 

- name: Start proxy server
  command: sudo forever start -o out.log -e err.log canary_LB.js