---
- name: Create Jenkins CLI destination directory
  file:
    path: "/opt/jenkins" 
    state: directory

- name: Get Jenkins CLI
  get_url:
    url: "http://{{ inventory_hostname }}:8090/jnlpJars/jenkins-cli.jar"
    dest: "/opt/jenkins/jenkins-cli.jar"
    mode: 0440
  register: jenkins_local_cli
  until: "'OK' in jenkins_local_cli.msg or 'file already exists' in jenkins_local_cli.msg"
  retries: 5
  delay: 10   

- name: Copy production job config file
  template:
    src: ./jobConfig/config.xml
    dest: /home/ubuntu 

- name: Copy canary job config file
  template:
    src: ./jobConfig/canary_config.xml
    dest: /home/ubuntu 

- name: Wait untils Jenkins web API is available
  shell: curl --head --silent http://{{ inventory_hostname }}:8090/cli/
  register: result
  until: result.stdout.find("200 OK") != -1
  retries: 12
  delay: 5

- name: Create job
  sudo: yes
  shell: "java -jar /opt/jenkins/jenkins-cli.jar -s http://{{ inventory_hostname }}:8090/ create-job checkboxio < config.xml"

- name: Create job
  sudo: yes
  shell: "java -jar /opt/jenkins/jenkins-cli.jar -s http://{{ inventory_hostname }}:8090/ create-job checkboxio_canary < canary_config.xml"
