---

- name: Create code directory
  file: path={{ code_directory }} state=directory

- name: Clone iTrust repository in VM home
  git: repo=https://{{lookup('env','gituser')}}:{{ lookup('env', 'gitpwd' )}}@github.ncsu.edu/ssreeni/iTrust-Local.git dest=/home/vagrant/code

- name: Clone iTrust repository
  git: repo=https://{{lookup('env','gituser')}}:{{ lookup('env', 'gitpwd' )}}@github.ncsu.edu/ssreeni/iTrust-Local.git dest=/var/lib/jenkins/workspace/itrust
