---
# This playbook deploys jenkins server and runs checkbox.io application

- name: Install and configure jenkins and run checkbox.io application
  hosts: nodes
  gather_facts: False
  become: yes
  become_user: root
  remote_user: root
  roles:
    - jenkins_jobs
